### PR TITLE
Add highlighting for string interpolation

### PR DESCRIPTION
**Pull request by nddrylliog**
It's coming in 0.9.8, so better be ready for it.

Also if someone can figure out why smartindent is being really stupid about ooc declarations, that'd be nice :)

### CODE REVIEW

**Comment by causal-agent** [comment]
Hey, since I'm no longer involved with ooc, do you want commit access to this repo? (Or I could transfer it to you or whatever, but that might break people's pathogen/vundle configurations)

**Comment by nddrylliog** [comment]
@programble sure, commit access works. I'm already grandfathering a few repos from former ooc contributors :)

**Comment by causal-agent** [comment]
Okay, I'll merge and give you access.

**Comment by nddrylliog** [comment]
Awesome, thanks :)

**Pull request merged**
